import turtle
def triangle60msg(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('medium spring green')
    turtle.begin_fill()
    turtle.forward(a)
    turtle.right(120)
    turtle.forward(a)
    turtle.right(120)
    turtle.forward(a)
    turtle.right(120)
    turtle.end_fill()

def triangle60t(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('tomato')
    turtle.begin_fill()
    turtle.forward(a)
    turtle.right(120)
    turtle.forward(a)
    turtle.right(120)
    turtle.forward(a)
    turtle.right(120)
    turtle.end_fill()


def trapezoidc(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('cyan')
    turtle.begin_fill()
    turtle.forward(a/2)
    turtle.right(60)
    turtle.forward(a/2)
    turtle.right(120)
    turtle.forward(a)
    turtle.right(120)
    turtle.forward(a/2)
    turtle.right(60)
    turtle.end_fill()



def paral(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('blueViolet')
    turtle.begin_fill()
    turtle.forward(a)
    turtle.right(45)
    turtle.forward(a/2)
    turtle.right(135)
    turtle.forward(a)
    turtle.right(45)
    turtle.forward(a/2)
    turtle.right(135)
    turtle.end_fill()

def triangle90dp(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('deep pink')
    turtle.begin_fill()
    turtle.forward(a)
    turtle.right(135)
    turtle.forward(a*(2**0.5))
    turtle.right(135)
    turtle.forward(a)
    turtle.right(90)
    turtle.end_fill()

def triangle90o(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('orange')
    turtle.begin_fill()
    turtle.forward(a)
    turtle.right(135)
    turtle.forward(a*(2**0.5))
    turtle.right(135)
    turtle.forward(a)
    turtle.right(90)
    turtle.end_fill()

def rombm(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('orange')
    turtle.begin_fill()
    turtle.left(45)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(135)
    turtle.end_fill()

def square(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('lime')
    turtle.begin_fill()
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.end_fill()

def pryam(x, y, a):
    turtle.up()
    turtle.setposition(x, y)
    turtle.down()
    turtle.color('magenta')
    turtle.begin_fill()
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a/2)
    turtle.right(90)
    turtle.forward(a)
    turtle.right(90)
    turtle.forward(a/2)
    turtle.right(90)
    turtle.end_fill()
def main():
    turtle.left(90)
    pryam(100, -100, 200)
    turtle.right(90)
    pryam(200, 46, 150)
    turtle.left(90)
    triangle60msg(350, -30, 76)
    turtle.right(90)
    paral(-310, 60, 240)
    turtle.left(135)
    triangle90dp(15, -25, 120)
    turtle.left(45)
    triangle90o(100,-25,85)
    turtle.right(225)
    triangle90dp(-310, 60, 120)
    turtle.done()

main()